In [0]:
import pandas as pd
import statsmodels.api as sm

In [2]:
file="https://github.com/VitorKamada/ECO6100/raw/master/Data/JTRAIN.DTA"
df = pd.read_stata(file)
df.head()

   year     fcode  employ       sales  ...  clavgsal  cgrant_1   chrsemp  clhrsemp
0  1987  410032.0   100.0  47000000.0  ...       NaN       NaN       NaN       NaN
1  1988  410032.0   131.0  43000000.0  ...  0.055570       0.0 -8.946565 -1.165385
2  1989  410032.0   123.0  49000000.0  ...  0.052644       0.0  0.198597  0.047832
3  1987  410440.0    12.0   1560000.0  ...       NaN       NaN       NaN       NaN
4  1988  410440.0    13.0   1970000.0  ...  0.046520       0.0  0.000000  0.000000

[5 rows x 30 columns]

In [3]:
df['const'] = 1
df = df[df['d88'] == 1]
reg1 = sm.OLS(df['lscrap'], df[['const', 'grant']], 
              missing='drop').fit()
print(reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 lscrap   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.019
Method:                 Least Squares   F-statistic:                   0.01948
Date:                Mon, 05 Aug 2019   Prob (F-statistic):              0.890
Time:                        19:06:15   Log-Likelihood:                -94.660
No. Observations:                  54   AIC:                             193.3
Df Residuals:                      52   BIC:                             197.3
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4085      0.241      1.698      0.095      -0.074       0.891
grant          0.0566      0.406      0.140      0.890      -0.757       0.870
==============================================================================
Omnibus:                        0.074   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.963   Jarque-Bera (JB):                0.086
Skew:                          -0.067   Prob(JB):                        0.958
Kurtosis:                       2.859   Cond. No.                         2.42
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [4]:
reg2 = sm.OLS(df['clscrap'], df[['const', 'cgrant']], 
              missing='drop').fit()
print(reg2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                clscrap   R-squared:                       0.067
Model:                            OLS   Adj. R-squared:                  0.049
Method:                 Least Squares   F-statistic:                     3.743
Date:                Mon, 05 Aug 2019   Prob (F-statistic):             0.0585
Time:                        19:06:15   Log-Likelihood:                -45.728
No. Observations:                  54   AIC:                             95.46
Df Residuals:                      52   BIC:                             99.43
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0574      0.097     -0.591      0.557      -0.252       0.138
cgrant        -0.3171      0.164     -1.935      0.058      -0.646       0.012
==============================================================================
Omnibus:                       20.851   Durbin-Watson:                   1.740
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              138.284
Skew:                           0.434   Prob(JB):                     9.38e-31
Kurtosis:                      10.791   Cond. No.                         2.42
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [5]:
import pandas as pd
import statsmodels.api as sm
file="https://github.com/VitorKamada/ECO6100/raw/master/Data/KIELMC.DTA"
df = pd.read_stata(file)
df.head()

   year  age   agesq  nbh  ...  nearinc  y81nrinc   rprice    lrprice
0  1978   48  2304.0    4  ...        1         0  60000.0  11.002100
1  1978   83  6889.0    4  ...        1         0  40000.0  10.596635
2  1978   58  3364.0    4  ...        1         0  34000.0  10.434115
3  1978   11   121.0    4  ...        1         0  63900.0  11.065075
4  1978   48  2304.0    4  ...        1         0  44000.0  10.691945

[5 rows x 25 columns]

In [6]:
df['const'] = 1
df['rprice'] = df['rprice']/1000

df81 = df[df['year'] == 1981]
reg1 = sm.OLS(df81['rprice'], df81[['const', 'nearinc']],
                    missing='drop').fit()
print(reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.159
Method:                 Least Squares   F-statistic:                     27.73
Date:                Mon, 05 Aug 2019   Prob (F-statistic):           5.14e-07
Time:                        19:06:15   Log-Likelihood:                -689.19
No. Observations:                 142   AIC:                             1382.
Df Residuals:                     140   BIC:                             1388.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        101.3075      3.093     32.754      0.000      95.192     107.423
nearinc      -30.6883      5.828     -5.266      0.000     -42.210     -19.167
==============================================================================
Omnibus:                       23.943   Durbin-Watson:                   1.380
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.601
Skew:                           0.832   Prob(JB):                     4.15e-09
Kurtosis:                       4.939   Cond. No.                         2.44
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [7]:
df78 = df[df['year'] == 1978]
reg2 = sm.OLS(df78['rprice'], df78[['const', 'nearinc']],
                    missing='drop').fit()
print(reg2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.082
Model:                            OLS   Adj. R-squared:                  0.076
Method:                 Least Squares   F-statistic:                     15.74
Date:                Mon, 05 Aug 2019   Prob (F-statistic):           0.000105
Time:                        19:06:15   Log-Likelihood:                -858.38
No. Observations:                 179   AIC:                             1721.
Df Residuals:                     177   BIC:                             1727.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         82.5172      2.654     31.094      0.000      77.280      87.754
nearinc      -18.8244      4.745     -3.968      0.000     -28.188      -9.461
==============================================================================
Omnibus:                      173.455   Durbin-Watson:                   1.707
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4526.710
Skew:                           3.520   Prob(JB):                         0.00
Kurtosis:                      26.609   Cond. No.                         2.42
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [8]:
reg3 = sm.OLS(df['rprice'], df[['const', 'y81', 'nearinc', 
              'y81nrinc']], missing='drop').fit()
print(reg3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 rprice   R-squared:                       0.174
Model:                            OLS   Adj. R-squared:                  0.166
Method:                 Least Squares   F-statistic:                     22.25
Date:                Mon, 05 Aug 2019   Prob (F-statistic):           4.22e-13
Time:                        19:06:15   Log-Likelihood:                -1547.8
No. Observations:                 321   AIC:                             3104.
Df Residuals:                     317   BIC:                             3119.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         82.5172      2.727     30.260      0.000      77.152      87.882
y81           18.7903      4.050      4.640      0.000      10.822      26.759
nearinc      -18.8244      4.875     -3.861      0.000     -28.416      -9.232
y81nrinc     -11.8639      7.457     -1.591      0.113     -26.535       2.807
==============================================================================
Omnibus:                      192.562   Durbin-Watson:                   1.557
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2462.070
Skew:                           2.217   Prob(JB):                         0.00
Kurtosis:                      15.822   Cond. No.                         6.05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.